# Generated by Django 2.0.7 on 2018-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Industry_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.IntegerField(default=0)),
                ('class_sub_code', models.IntegerField(default=0)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
    ]
