# Generated by Django 2.0.7 on 2018-07-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EO_Pricing_Model_Base_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_sales', models.FloatField(blank=True, db_index=True)),
                ('base_rate', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EO_Pricing_Model_Deductible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductible_amount', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('multiplier', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EO_Pricing_Model_Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurence_limit', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('increased_limit_factor', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EO_Pricing_Model_Marginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_sales', models.FloatField(blank=True, db_index=True)),
                ('marginal_price', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Errors_Omissions_Policy_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_sub_code', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('need_for_policy', models.CharField(blank=True, max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard_Rate_Multiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_level_rating', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('rate_multiplier', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NAIC_Industry_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('industry', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NAIC_Sub_Industry_Code_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.IntegerField(blank=True, max_length=11)),
                ('class_sub_code', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NAIC_Sub_Industry_Code_54',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.IntegerField(blank=True, max_length=11)),
                ('class_sub_code', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NAIC_Sub_Industry_Hazard_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_sub_code', models.IntegerField(blank=True, db_index=True, max_length=11)),
                ('hazard_level_rating', models.IntegerField(blank=True, max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_Industry_Code',
        ),
    ]
