# Generated by Django 2.0.7 on 2018-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20180703_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naic_sub_industry_code_11',
            name='class_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterModelTable(
            name='eo_pricing_model_base_rate',
            table='EO_PRICING_MODEL_BASE_RATE',
        ),
        migrations.AlterModelTable(
            name='eo_pricing_model_deductible',
            table='EO_PRICING_MODEL_DEDUCTIBLE',
        ),
        migrations.AlterModelTable(
            name='eo_pricing_model_limit',
            table='EO_PRICING_MODEL_LIMIT',
        ),
        migrations.AlterModelTable(
            name='eo_pricing_model_marginal',
            table='EO_PRICING_MODEL_MARGINAL',
        ),
        migrations.AlterModelTable(
            name='errors_omissions_policy_details',
            table='ERRORS_OMISSIONS_POLICY_DETAILS',
        ),
        migrations.AlterModelTable(
            name='hazard_rate_multiplier',
            table='HAZARD_RATE_MULTIPLIER',
        ),
        migrations.AlterModelTable(
            name='naic_industry_code',
            table='NAIC_INDUSTRY_CODE',
        ),
        migrations.AlterModelTable(
            name='naic_sub_industry_hazard_rating',
            table='NAIC_SUB_INDUSTRY_HAZARD_RATING',
        ),
    ]
